services:
  traefik:
    container_name: traefik-proxy
    image: traefik:saintnectaire
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/tls.yml:/etc/traefik/tls.yml:ro
      - ./certs:/etc/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      proxy: ~

  mailcatcher:
    image: schickling/mailcatcher
    container_name: traefik-mailcatcher
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.local`)"
      - "traefik.http.routers.mailcatcher.tls=true"
      - "traefik.http.routers.mailcatcher.entrypoints=websecure"
      - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
    networks:
      proxy: ~

networks:
  proxy:
    name: "traefik-proxy-network"
    driver: bridge
