# ─── Couleurs ──────────────────────────────────────────────────────────────────

RESET  := \033[0m
BOLD   := \033[1m
GREEN  := \033[32m
YELLOW := \033[33m
CYAN   := \033[36m
RED    := \033[31m

DOCKER_COMPOSE=docker compose

##
## ----------------------------------------------------------------------------
##   Docker
## ----------------------------------------------------------------------------
##

docker-init: ## Build and start docker
	@echo "$(CYAN)▶ Docker build...$(RESET)"
	$(DOCKER_COMPOSE) down -v
	$(DOCKER_COMPOSE) up -d --remove-orphans && $(DOCKER_COMPOSE) logs
	@echo "$(GREEN) ✔ Docker is ready$(RESET)"

docker-start: ## Start docker
	$(DOCKER_COMPOSE) start

docker-stop: ## Stop docker
	$(DOCKER_COMPOSE) stop

docker-restart: ## Restart project
	$(DOCKER_COMPOSE) restart

docker-logs: ## Follow logs generated by all containers
	$(DOCKER_COMPOSE) logs -f --tail=0

docker-logs-full: ## Follow logs generated by all containers from the containers creation
	$(DOCKER_COMPOSE) logs -f

.PHONY: docker-init docker-build docker-start docker-stop docker-restart docker-logs docker-logs-full

##
## ----------------------------------------------------------------------------
##   Shell
## ----------------------------------------------------------------------------
##

traefik-shell: ## Access traefik container shell
	$(DOCKER_COMPOSE) exec traefik sh

.PHONY: traefik-shell

##
## ----------------------------------------------------------------------------
##   Certificates
## ----------------------------------------------------------------------------
##

-include .env

mkcert: ## Generate mkcert certificates for dev (domains loaded from .env file)
	@echo "$(CYAN)▶ Generating mkcert certificates...$(RESET)"
	mkcert -install
	mkcert -cert-file certs/wildcard.dev.local.crt -key-file certs/wildcard.dev.local.key $(MKCERT_DOMAINS)
	@echo "$(GREEN) ✔ mkcert certificates generated$(RESET)"

.PHONY: mkcert


.DEFAULT_GOAL := help
.PHONY: help
help: ## Show this help
	@printf "$(CYAN)  ┌──────────────────────────────────────────────────────┐$(RESET)\n"
	@printf "$(CYAN)  │   $(GREEN)██╗   ██╗ ██████╗ ██╗      ██████╗ $(RESET)	$(CYAN)         │$(RESET)\n"
	@printf "$(CYAN)  │   $(GREEN)╚██╗ ██╔╝██╔═══██╗██║     ██╔═══██╗$(RESET)	$(CYAN)         │$(RESET)\n"
	@printf "$(CYAN)  │    $(GREEN)╚████╔╝ ██║   ██║██║     ██║   ██║$(RESET)	$(CYAN)         │$(RESET)\n"
	@printf "$(CYAN)  │     $(GREEN)╚██╔╝  ██║   ██║██║     ██║   ██║$(RESET)	$(CYAN)	 │$(RESET)\n"
	@printf "$(CYAN)  │      $(GREEN)██║   ╚██████╔╝███████╗╚██████╔╝$(RESET)	$(CYAN)         │$(RESET)\n"
	@printf "$(CYAN)  │      $(GREEN)╚═╝    ╚═════╝ ╚══════╝ ╚═════╝ $(RESET)	$(CYAN)         │$(RESET)\n"
	@printf "$(CYAN)  │$(RESET)                                                     $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │  $(BOLD)$(GREEN)🚀 Global Docker Config for Dev 🚀$(RESET)                 $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │  $(GREEN)   - Traefik $(RESET)                                      $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │  $(GREEN)   - Mailpit $(RESET)                                      $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │  $(GREEN)   - Prometheus/Grafana $(RESET)                           $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │  $(GREEN)   - Dozzle $(RESET)                                       $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  │$(RESET)                                                     $(CYAN) │$(RESET)\n"
	@printf "$(CYAN)  └──────────────────────────────────────────────────────┘$(RESET)\n"
	@printf "\n"
	@egrep -h '(^[a-zA-Z0-9_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' \
		| sed -e 's/\[32m##/[33m/'
