DOCKER_COMPOSE=docker compose

##
## ----------------------------------------------------------------------------
##   Docker
## ----------------------------------------------------------------------------
##

docker-init: ## Build and start docker
	$(DOCKER_COMPOSE) down -v
	$(DOCKER_COMPOSE) up -d --remove-orphans && $(DOCKER_COMPOSE) logs

docker-start: ## Start docker
	$(DOCKER_COMPOSE) start

docker-stop: ## Stop docker
	$(DOCKER_COMPOSE) stop

docker-restart: ## Restart project
	$(DOCKER_COMPOSE) restart

docker-logs: ## Follow logs generated by all containers
	$(DOCKER_COMPOSE) logs -f --tail=0

docker-logs-full: ## Follow logs generated by all containers from the containers creation
	$(DOCKER_COMPOSE) logs -f

.PHONY: docker-init docker-build docker-start docker-stop docker-restart docker-logs docker-logs-full

##
## ----------------------------------------------------------------------------
##   Certificates
## ----------------------------------------------------------------------------
##
generate-ssl-certificate: ## Generate self-signed certificate for dev
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
		-keyout ./certs/default_key.pem \ 
		-out ./certs/default_cert.pem \ 
		-subj "/C=FR/ST=Local/L=Local/O=Relight/OU=Development/CN=*.local" \
		-addext "subjectAltName = DNS:*.local,DNS:localhost"

.PHONY:generate-ssl-certificate


.DEFAULT_GOAL := help
.PHONY: help
help: ## Show this help
	@egrep -h '(^[a-zA-Z0-9_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' \
		| sed -e 's/\[32m##/[33m/'