tls:
  certificates:
    - certFile: /etc/certs/wildcard.dev.local.crt
      keyFile: /etc/certs/wildcard.dev.local.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/wildcard.dev.local.crt
        keyFile: /etc/certs/wildcard.dev.local.key
