api:
 dashboard: true
 insecure: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true

serversTransport:
  insecureSkipVerify: true
  
providers:
  file:
    filename: /etc/traefik/tls.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-proxy-network"


log:
  level: DEBUG
  format: common

accessLog: {}
