api:
 dashboard: true
 insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-proxy-network"

# certificatesResolvers:
#   ovh:
#     acme:
#       email: "{{ traefik_acme_email }}"
#       storage: "/etc/traefik/acme.json"
#       tlsChallenge: {}
#       # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       dnsChallenge:
#         provider: ovh

log:
  level: DEBUG
  format: common

accessLog: {}